version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elasticsearch771
    environment:
      - "TZ=Asia/Tokyo"
      - ELASTIC_PASSWORD=changeme
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - "discovery.type=single-node"
      - "http.max_content_length=200m"
      - "network.host=_local_,_site_"
      - "script.painless.regex.enabled=true"
      - "xpack.monitoring.collection.enabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./es/share/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./es/share/elasticsearch.log:/usr/share/elasticsearch/logs/docker-cluster.log
    ports:
      - 9200:9200
    networks:
      - esnet
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: kibana771
    ports:
      - 5601:5601
    environment:
      - "TZ=Asia/Tokyo"
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=kibana"
      - "SERVER_HOST=0.0.0.0"
      - "LOGGING_DEST=/usr/share/kibana/kibana.log"
    volumes:
      - ./kibana/kibana.log:/usr/share/kibana/kibana.log
    networks:
      - esnet
    restart: always
    
  togoannotator:
    build: 
      context: ./
      dockerfile: ./ta/Dockerfile
#プロキシ環境下では53から55行目のコメントアウトを外す
#      args:
#        http_proxy: http://<プロキシアドレス>
#        https_proxy: http://<プロキシアドレス>
    image: ta_test
    container_name: ta
    environment:
      - TA_URL=${TA_URL:-http://localhost:5000}
    volumes:
      - ./log/production.log:/opt/togoannotator/ta/WebService/log/production.log
      - ./dictionary:/opt/togoannotator/ta/WebService/dictionary
    ports:
      - 5100:5100
    networks:
     - esnet
    restart: always

  nginx:
    image: nginx:1.17.9
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 5000:5000
    depends_on:
      - togoannotator
    networks:
      - esnet
    restart: always

networks:
  esnet:
