version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch1
    environment:
      - "TZ=Asia/Tokyo"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
      - "discovery.zen.ping.unicast.hosts=elasticsearch2,elasticsearch3"
      - "network.host=_local_,_site_"
      - "http.max_content_length=200m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
      - ./es/share/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    ports:
      - 19200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch2
    environment:
      - "TZ=Asia/Tokyo"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch3"
      - "network.host=_local_,_site_"
      - "http.max_content_length=200m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
      - ./es/share/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
      - esnet
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch3
    environment:
      - "TZ=Asia/Tokyo"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
      - "network.host=_local_,_site_"
      - "http.max_content_length=200m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata3:/usr/share/elasticsearch/data
      - ./es/share/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
      - esnet

  kibana1:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana1
    environment:
      - "TZ=Asia/Tokyo"
      - "ELASTICSEARCH_URL=http://elasticsearch1:9200"
      - "SERVER_NAME=kibana"
      - "SERVER_HOST=0.0.0.0"
    ports:
      - 15601:5601

    links:
      - "elasticsearch1:elasticsearch1"
    networks:
      - esnet


networks:
  esnet:
